### PR TITLE
Use a custom (manual) build of jmx_exporter (IDR-0.4.2)

### PR DESCRIPTION
**Pull request by manics**
This installs a custom (manual) build of jmx_exporter to test whether https://github.com/prometheus/jmx_exporter/issues/156 is fixed by https://github.com/prometheus/jmx_exporter/pull/162

# Details:

Repository: https://github.com/prometheus/jmx_exporter
Commit:
```
commit 5b180affbefa445088d4608b9640ca404ce91ae2
Author: Leo Gomes <leonardo.f.gomes@gmail.com>
Date:   Mon Jul 17 14:34:30 2017 +0200

    Use simple HTTP Server (#162)
```
Build: `docker run -it --rm -v $PWD:/build -w /build maven mvn package`
Artifact: `jmx_prometheus_javaagent/target/jmx_prometheus_javaagent-0.10-SNAPSHOT.jar`

### CODE REVIEW

**Comment by joshmoore** [comment]
Can this be updated to use jmx_exporter-162 now?

**Comment by manics** [comment]
Yes, but it depends on how strict we want to be about recording component versions since the new version won't be deployed on the current production. I've already got a commit ready https://github.com/manics/ansible-role-prometheus-jmx/commit/225507e159e61d96123ff05e9f7cc7f362993bfb

**Comment by joshmoore** [comment]
Do please push. Recording something reproducible from non-dev resources seems preferable to having it match exactly.

**Comment by manics** [comment]
pushed

**Comment by joshmoore** [comment]
Cheers. 0.2.0 or 0.1.1?

**Comment by manics** [comment]
Non-breaking, `0.1.1`

**Pull request merged**
